--Creación de la TableSpace para los datos
CREATE TABLESPACE CURSODB_DAT 
    DATAFILE 'C:\ORACLE\ORADATA\ORCL\CURSODB_DAT.DBF' SIZE 5242880 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL;

--Creación de la TableSpace para los indices
CREATE TABLESPACE CURSODB_IDX 
    DATAFILE 'C:\ORACLE\ORADATA\ORCL\CURSODB_IDX.DBF' SIZE 5242880 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL;

--Si sale error al crear usuario ejecutar
alter session set "_ORACLE_SCRIPT"=true;

--Creación de usuario para las TableSpaces creadas anteriormente
CREATE USER "CURSODB" PROFILE "DEFAULT" IDENTIFIED BY "cursoDB2025"
DEFAULT TABLESPACE "CURSODB_DAT" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

--Permisos para el usuario
GRANT "CONNECT" TO "CURSODB";
GRANT "RESOURCE" TO "CURSODB";

--Permisos sobre los objetos
GRANT ALTER ANY INDEX TO "CURSODB";
GRANT ALTER ANY SEQUENCE TO "CURSODB";
GRANT ALTER ANY TABLE TO "CURSODB";
GRANT ALTER ANY TRIGGER TO "CURSODB";
GRANT CREATE ANY INDEX TO "CURSODB";
GRANT CREATE ANY SEQUENCE TO "CURSODB";
GRANT CREATE ANY SYNONYM TO "CURSODB";
GRANT CREATE ANY TABLE TO "CURSODB";
GRANT CREATE ANY TRIGGER TO "CURSODB";
GRANT CREATE ANY VIEW TO "CURSODB";
GRANT CREATE PROCEDURE TO "CURSODB";
GRANT CREATE PUBLIC SYNONYM TO "CURSODB";
GRANT CREATE TRIGGER TO "CURSODB";
GRANT CREATE VIEW TO "CURSODB";
GRANT DELETE ANY TABLE TO "CURSODB";
GRANT DROP ANY INDEX TO "CURSODB";
GRANT DROP ANY SEQUENCE TO "CURSODB";
GRANT DROP ANY TABLE TO "CURSODB";
GRANT DROP ANY TRIGGER TO "CURSODB";
GRANT DROP ANY VIEW TO "CURSODB";
GRANT INSERT ANY TABLE TO "CURSODB";
GRANT QUERY REWRITE TO "CURSODB";
GRANT SELECT ANY TABLE TO "CURSODB";
GRANT UNLIMITED TABLESPACE TO "CURSODB";