--Tabla TBL_CLIENTES
CREATE TABLE CURSODB.TBL_CLIENTES
(
    NIT NUMBER NOT NULL,
    RAZON_SOCIAL VARCHAR2(100) NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(50),
    TELEFONO VARCHAR2(15) NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_CLIENTES  IS 'CLIENTES';
COMMENT ON COLUMN CURSODB.TBL_CLIENTES.NIT IS 'NIT del cliente';
COMMENT ON COLUMN CURSODB.TBL_CLIENTES.RAZON_SOCIAL IS 'Razon solcial del cliente';
COMMENT ON COLUMN CURSODB.TBL_CLIENTES.DIRECCION IS 'Direccion del cliente';
COMMENT ON COLUMN CURSODB.TBL_CLIENTES.EMAIL IS 'CEmail del cliente';
COMMENT ON COLUMN CURSODB.TBL_CLIENTES.TELEFONO IS 'Telefono del cliente';

CREATE UNIQUE INDEX IDX_PK_NIT_CLIENTES
	ON CURSODB.TBL_CLIENTES(NIT)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_CLIENTES ADD CONSTRAINT PK_NIT_CLIENTES PRIMARY KEY (NIT)
    USING INDEX IDX_PK_NIT_CLIENTES;

--Tabla TBL_ENCARGADOS
CREATE TABLE CURSODB.TBL_ENCARGADOS
(
    COD_ENCARGADO NUMBER NOT NULL,
	NIT_CLIENTE NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(15) NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_ENCARGADOS  IS 'ENCARGADOS';
COMMENT ON COLUMN CURSODB.TBL_ENCARGADOS.COD_ENCARGADO IS 'Codigo del encargado del cliente';
COMMENT ON COLUMN CURSODB.TBL_ENCARGADOS.NIT_CLIENTE IS 'NIT del cliente';
COMMENT ON COLUMN CURSODB.TBL_ENCARGADOS.NOMBRE IS 'Nombre del encargado del cliente';
COMMENT ON COLUMN CURSODB.TBL_ENCARGADOS.TELEFONO IS 'Telefono del encargado del cliente';

CREATE UNIQUE INDEX IDX_PK_COD_ENCARGA_ENCARGADOS
	ON CURSODB.TBL_ENCARGADOS(COD_ENCARGADO)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_ENCARGADOS ADD CONSTRAINT PK_COD_ENCARGADO_ENCARGADOS PRIMARY KEY (COD_ENCARGADO)
    USING INDEX IDX_PK_COD_ENCARGA_ENCARGADOS;
	
ALTER TABLE CURSODB.TBL_ENCARGADOS ADD CONSTRAINT FK_ENCARGADOS_CLIENTES
	FOREIGN KEY (NIT_CLIENTE) REFERENCES CURSODB.TBL_CLIENTES(NIT);
	
--Tabla TBL_TRANSPORTADORES
CREATE TABLE CURSODB.TBL_TRANSPORTADORES
(
    COD_TRANSPORTADOR NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(15) NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_TRANSPORTADORES  IS 'TRANSPORTADORES';
COMMENT ON COLUMN CURSODB.TBL_TRANSPORTADORES.COD_TRANSPORTADOR IS 'Codigo del transportador';
COMMENT ON COLUMN CURSODB.TBL_TRANSPORTADORES.NOMBRE IS 'Nombre del transportador';
COMMENT ON COLUMN CURSODB.TBL_TRANSPORTADORES.TELEFONO IS 'Telefono del transportador';

CREATE UNIQUE INDEX IDX_PK_COD_TRANSPOR_TRANSPORS
	ON CURSODB.TBL_TRANSPORTADORES(COD_TRANSPORTADOR)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_TRANSPORTADORES ADD CONSTRAINT PK_COD_TRANSPOR_TRANSPORS PRIMARY KEY (COD_TRANSPORTADOR)
    USING INDEX IDX_PK_COD_TRANSPOR_TRANSPORS;
	
--Tabla TBL_VENDEDORES
CREATE TABLE CURSODB.TBL_VENDEDORES
(
    COD_VENDEDOR NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_VENDEDORES  IS 'VENDEDORES';
COMMENT ON COLUMN CURSODB.TBL_VENDEDORES.COD_VENDEDOR IS 'Codigo del vendedor';
COMMENT ON COLUMN CURSODB.TBL_VENDEDORES.NOMBRE IS 'Nombre del vendedor';

CREATE UNIQUE INDEX IDX_PK_COD_VENDEDOR_VENDEDORES
	ON CURSODB.TBL_VENDEDORES(COD_VENDEDOR)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_VENDEDORES ADD CONSTRAINT PK_COD_VENDEDOR_VENDEDORES PRIMARY KEY (COD_VENDEDOR)
    USING INDEX IDX_PK_COD_VENDEDOR_VENDEDORES;
	
--Tabla TBL_ESTADOS
CREATE TABLE CURSODB.TBL_ESTADOS
(
    COD_ESTADO NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_ESTADOS  IS 'ESTADOS';
COMMENT ON COLUMN CURSODB.TBL_ESTADOS.COD_ESTADO IS 'Codigo del estado';
COMMENT ON COLUMN CURSODB.TBL_ESTADOS.NOMBRE IS 'Nombre del estado';

CREATE UNIQUE INDEX IDX_PK_COD_ESTADO_ESTADOS
	ON CURSODB.TBL_ESTADOS(COD_ESTADO)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_ESTADOS ADD CONSTRAINT PK_COD_ESTADO_ESTADOS PRIMARY KEY (COD_ESTADO)
    USING INDEX IDX_PK_COD_ESTADO_ESTADOS;
	
--Tabla TBL_ENTRADAS
CREATE TABLE CURSODB.TBL_ENTRADAS
(
    COD_ENTRADA NUMBER NOT NULL,
    FECHA_ENTRADA DATE NOT NULL,
    REMESA VARCHAR2(50) NOT NULL,
    ORIGEN VARCHAR2(50),
    OBSERVACIONES VARCHAR2(4000)
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_ENTRADAS  IS 'ENTRADAS';
COMMENT ON COLUMN CURSODB.TBL_ENTRADAS.COD_ENTRADA IS 'Codigo de la entrada';
COMMENT ON COLUMN CURSODB.TBL_ENTRADAS.FECHA_ENTRADA IS 'Fecha de la entrada';
COMMENT ON COLUMN CURSODB.TBL_ENTRADAS.REMESA IS 'Remesa de la entrada';
COMMENT ON COLUMN CURSODB.TBL_ENTRADAS.ORIGEN IS 'Origen de la entrada';
COMMENT ON COLUMN CURSODB.TBL_ENTRADAS.OBSERVACIONES IS 'Observaciones de la entrada';

CREATE UNIQUE INDEX IDX_PK_COD_ENTRADA_ENTRADAS
	ON CURSODB.TBL_ENTRADAS(COD_ENTRADA)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_ENTRADAS ADD CONSTRAINT PK_COD_ENTRADA_ENTRADAS PRIMARY KEY (COD_ENTRADA)
    USING INDEX IDX_PK_COD_ENTRADA_ENTRADAS;
	
--Tabla TBL_PRODUCTOS
CREATE TABLE CURSODB.TBL_PRODUCTOS
(
    COD_PRODUCTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    PESOXUNIDAD NUMBER NOT NULL,
    UNIDADXEMBALAJE NUMBER NOT NULL,
    PESOXEMBALAJE NUMBER NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_PRODUCTOS  IS 'PRODUCTOS';
COMMENT ON COLUMN CURSODB.TBL_PRODUCTOS.COD_PRODUCTO IS 'Codigo del producto';
COMMENT ON COLUMN CURSODB.TBL_PRODUCTOS.NOMBRE IS 'Nombre del producto';
COMMENT ON COLUMN CURSODB.TBL_PRODUCTOS.PESOXUNIDAD IS 'Peso por unidad del producto';
COMMENT ON COLUMN CURSODB.TBL_PRODUCTOS.UNIDADXEMBALAJE IS 'Unidades por embalaje del producto';
COMMENT ON COLUMN CURSODB.TBL_PRODUCTOS.PESOXEMBALAJE IS 'Peso por embalaje del producto';

CREATE UNIQUE INDEX IDX_PK_COD_PRODUCTO_PRODUCTOS
	ON CURSODB.TBL_PRODUCTOS(COD_PRODUCTO)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_PRODUCTOS ADD CONSTRAINT PK_COD_PRODUCTO_PRODUCTOS PRIMARY KEY (COD_PRODUCTO)
    USING INDEX IDX_PK_COD_PRODUCTO_PRODUCTOS;
	
--Tabla TBL_INVENTARIOS
CREATE TABLE CURSODB.TBL_INVENTARIOS
(
    COD_PRODUCTO NUMBER NOT NULL,
    INVEN_PISO1 NUMBER NOT NULL,
    INVEN_PISO2 NUMBER NOT NULL,
    INVEN_TOTAL NUMBER NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_INVENTARIOS  IS 'INVENTARIOS';
COMMENT ON COLUMN CURSODB.TBL_INVENTARIOS.COD_PRODUCTO IS 'Codigo del producto';
COMMENT ON COLUMN CURSODB.TBL_INVENTARIOS.INVEN_PISO1 IS 'Inventario del piso 1 del producto';
COMMENT ON COLUMN CURSODB.TBL_INVENTARIOS.INVEN_PISO2 IS 'Inventario del piso 2 del producto';
COMMENT ON COLUMN CURSODB.TBL_INVENTARIOS.INVEN_TOTAL IS 'Inventario total (piso 1 + piso 2) del producto';

CREATE UNIQUE INDEX IDX_PK_COD_PRODUCTO_INVENTARIOS
	ON CURSODB.TBL_INVENTARIOS(COD_PRODUCTO)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_INVENTARIOS ADD CONSTRAINT PK_COD_PRODUCTO_INVENTARIOS PRIMARY KEY (COD_PRODUCTO)
    USING INDEX IDX_PK_COD_PRODUCTO_INVENTARIOS;
	
ALTER TABLE CURSODB.TBL_INVENTARIOS ADD CONSTRAINT FK_INVENTARIOS_PRODUCTOS
	FOREIGN KEY (COD_PRODUCTO) REFERENCES CURSODB.TBL_PRODUCTOS(COD_PRODUCTO);
	
--Tabla TBL_LOTES
CREATE TABLE CURSODB.TBL_LOTES
(
    COD_LOTE VARCHAR2(20) NOT NULL,
	COD_PRODUCTO NUMBER NOT NULL,
    FECHA_LOTE DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_LOTES  IS 'LOTES';
COMMENT ON COLUMN CURSODB.TBL_LOTES.COD_LOTE IS 'Codigo del lote';
COMMENT ON COLUMN CURSODB.TBL_LOTES.COD_PRODUCTO IS 'Codigo del producto';
COMMENT ON COLUMN CURSODB.TBL_LOTES.FECHA_LOTE IS 'Fecha de fabricacion del lote';
COMMENT ON COLUMN CURSODB.TBL_LOTES.FECHA_VENCIMIENTO IS 'Fecha de vencimiento del lote';

CREATE UNIQUE INDEX IDX_PK_COD_LOTE_LOTES
	ON CURSODB.TBL_LOTES(COD_LOTE)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_LOTES ADD CONSTRAINT PK_COD_LOTE_LOTES PRIMARY KEY (COD_LOTE)
    USING INDEX IDX_PK_COD_LOTE_LOTES;
	
ALTER TABLE CURSODB.TBL_LOTES ADD CONSTRAINT FK_LOTES_PRODUCTOS
	FOREIGN KEY (COD_PRODUCTO) REFERENCES CURSODB.TBL_PRODUCTOS(COD_PRODUCTO);
	
--Tabla TBL_DETALLEENTRADAS
CREATE TABLE CURSODB.TBL_DETALLEENTRADAS
(
    COD_PRODUCTO NUMBER NOT NULL,
	COD_ENTRADA NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_DETALLEENTRADAS  IS 'DETALLE ENTRADAS';
COMMENT ON COLUMN CURSODB.TBL_DETALLEENTRADAS.COD_PRODUCTO IS 'Codigo del producto';
COMMENT ON COLUMN CURSODB.TBL_DETALLEENTRADAS.COD_ENTRADA IS 'Codigo de la entrada';
COMMENT ON COLUMN CURSODB.TBL_DETALLEENTRADAS.CANTIDAD IS 'Cantidad de producto que ingresa en la entrada';

CREATE UNIQUE INDEX IDX_PK_CODPRO_CODENT_DETENT
	ON CURSODB.TBL_DETALLEENTRADAS(COD_PRODUCTO, COD_ENTRADA)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_DETALLEENTRADAS ADD CONSTRAINT PK_CODPRO_CODENT_DETENT PRIMARY KEY (COD_PRODUCTO, COD_ENTRADA)
    USING INDEX IDX_PK_CODPRO_CODENT_DETENT;
	
ALTER TABLE CURSODB.TBL_DETALLEENTRADAS ADD CONSTRAINT FK_DETALLEENTRADAS_PRODUCTOS
	FOREIGN KEY (COD_PRODUCTO) REFERENCES CURSODB.TBL_PRODUCTOS(COD_PRODUCTO);
	
ALTER TABLE CURSODB.TBL_DETALLEENTRADAS ADD CONSTRAINT FK_DETALLEENTRADAS_ENTRADAS
	FOREIGN KEY (COD_ENTRADA) REFERENCES CURSODB.TBL_ENTRADAS(COD_ENTRADA);
	
--Tabla TBL_ORDENPEDIDOS
CREATE TABLE CURSODB.TBL_ORDENPEDIDOS
(
    COD_ORDEN VARCHAR2(20) NOT NULL,
    NIT_CLIENTE NUMBER NOT NULL,
    COD_VENDEDOR NUMBER NOT NULL,
    COD_ESTADO NUMBER NOT NULL,
    FECHA_PEDIDO DATE NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_ORDENPEDIDOS  IS 'ORDENES PEDIDOS';
COMMENT ON COLUMN CURSODB.TBL_ORDENPEDIDOS.COD_ORDEN IS 'Codigo de la orden de pedido';
COMMENT ON COLUMN CURSODB.TBL_ORDENPEDIDOS.NIT_CLIENTE IS 'NIT del cliente';
COMMENT ON COLUMN CURSODB.TBL_ORDENPEDIDOS.COD_VENDEDOR IS 'Codigo del vendedor';
COMMENT ON COLUMN CURSODB.TBL_ORDENPEDIDOS.COD_ESTADO IS 'Codigo del estado de la orden de pedido';
COMMENT ON COLUMN CURSODB.TBL_ORDENPEDIDOS.FECHA_PEDIDO IS 'Fecha que se realizo el pedido';

CREATE UNIQUE INDEX IDX_PK_COD_ORDEN_ORDENPEDIDOS
	ON CURSODB.TBL_ORDENPEDIDOS(COD_ORDEN)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_ORDENPEDIDOS ADD CONSTRAINT PK_COD_ORDEN_ORDENPEDIDOS PRIMARY KEY (COD_ORDEN)
    USING INDEX IDX_PK_COD_ORDEN_ORDENPEDIDOS;
	
ALTER TABLE CURSODB.TBL_ORDENPEDIDOS ADD CONSTRAINT FK_ORDENPEDIDOS_CLIENTES
	FOREIGN KEY (NIT_CLIENTE) REFERENCES CURSODB.TBL_CLIENTES(NIT);
	
ALTER TABLE CURSODB.TBL_ORDENPEDIDOS ADD CONSTRAINT FK_ORDENPEDIDOS_VENDEDORES
	FOREIGN KEY (COD_VENDEDOR) REFERENCES CURSODB.TBL_VENDEDORES(COD_VENDEDOR);
	
ALTER TABLE CURSODB.TBL_ORDENPEDIDOS ADD CONSTRAINT FK_ORDENPEDIDOS_ESTADOS
	FOREIGN KEY (COD_ESTADO) REFERENCES CURSODB.TBL_ESTADOS(COD_ESTADO);
	
--Tabla TBL_FACTURAS
CREATE TABLE CURSODB.TBL_FACTURAS
(
    COD_FACTURA VARCHAR2(20) NOT NULL,
	COD_ORDEN VARCHAR2(20) NOT NULL,
    COD_TRANSPORTADOR NUMBER NOT NULL,
    IMAGEN_FACTURA VARCHAR2(200),
    TOTALPESO NUMBER NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_FACTURAS  IS 'FACTURAS';
COMMENT ON COLUMN CURSODB.TBL_FACTURAS.COD_FACTURA IS 'Codigo de la factura';
COMMENT ON COLUMN CURSODB.TBL_FACTURAS.COD_ORDEN IS 'Codigo de la orden de pedido';
COMMENT ON COLUMN CURSODB.TBL_FACTURAS.COD_TRANSPORTADOR IS 'Codigo del transportador';
COMMENT ON COLUMN CURSODB.TBL_FACTURAS.IMAGEN_FACTURA IS 'URL de donde se almacena la imagen de la factura';
COMMENT ON COLUMN CURSODB.TBL_FACTURAS.TOTALPESO IS 'Peso total de los productos';

CREATE UNIQUE INDEX IDX_PK_COD_FACTURA_FACTURAS
	ON CURSODB.TBL_FACTURAS(COD_FACTURA)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_FACTURAS ADD CONSTRAINT PK_COD_FACTURA_FACTURAS PRIMARY KEY (COD_FACTURA)
    USING INDEX IDX_PK_COD_FACTURA_FACTURAS;
	
ALTER TABLE CURSODB.TBL_FACTURAS ADD CONSTRAINT FK_FACTURAS_ORDENPEDIDOS
	FOREIGN KEY (COD_ORDEN) REFERENCES CURSODB.TBL_ORDENPEDIDOS(COD_ORDEN);
	
ALTER TABLE CURSODB.TBL_FACTURAS ADD CONSTRAINT FK_FACTURAS_TRANSPORTADORES
	FOREIGN KEY (COD_TRANSPORTADOR) REFERENCES CURSODB.TBL_TRANSPORTADORES(COD_TRANSPORTADOR);
	
--Tabla TBL_DETALLEPEDIDOS
CREATE TABLE CURSODB.TBL_DETALLEPEDIDOS
(
    COD_ORDEN VARCHAR2(20) NOT NULL,
	COD_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
	TOTAL_CAJAS NUMBER NOT NULL,
	PESOXCAJA NUMBER NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_DETALLEPEDIDOS  IS 'DETALLE PEDIDOS';
COMMENT ON COLUMN CURSODB.TBL_DETALLEPEDIDOS.COD_ORDEN IS 'Codigo de la orden de pedido';
COMMENT ON COLUMN CURSODB.TBL_DETALLEPEDIDOS.COD_PRODUCTO IS 'Codigo del producto';
COMMENT ON COLUMN CURSODB.TBL_DETALLEPEDIDOS.CANTIDAD IS 'Cantidad de producto en el pedido';
COMMENT ON COLUMN CURSODB.TBL_DETALLEPEDIDOS.TOTAL_CAJAS IS 'Total de cajas en el pedido';
COMMENT ON COLUMN CURSODB.TBL_DETALLEPEDIDOS.PESOXCAJA IS 'Peso por caja en el pedido';

CREATE UNIQUE INDEX IDX_PK_CODORD_CODPRO_DETPED
	ON CURSODB.TBL_DETALLEPEDIDOS(COD_ORDEN, COD_PRODUCTO)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_DETALLEPEDIDOS ADD CONSTRAINT PK_CODORD_CODPRO_DETPED PRIMARY KEY (COD_ORDEN, COD_PRODUCTO)
    USING INDEX IDX_PK_CODORD_CODPRO_DETPED;

ALTER TABLE CURSODB.TBL_DETALLEPEDIDOS ADD CONSTRAINT FK_DETALLEPEDIDOS_ENTRADAS
	FOREIGN KEY (COD_ORDEN) REFERENCES CURSODB.TBL_ORDENPEDIDOS(COD_ORDEN);
	
ALTER TABLE CURSODB.TBL_DETALLEPEDIDOS ADD CONSTRAINT FK_DETALLEPEDIDOS_PRODUCTOS
	FOREIGN KEY (COD_PRODUCTO) REFERENCES CURSODB.TBL_PRODUCTOS(COD_PRODUCTO);
	
--Tabla TBL_HISTORICOSINVEN
CREATE TABLE CURSODB.TBL_HISTORICOSINVEN
(
    COD_HISTORICO NUMBER NOT NULL,
	COD_PRODUCTO NUMBER NOT NULL,
	NOMBRE VARCHAR2(100) NOT NULL,
    PESOXUNIDAD NUMBER NOT NULL,
	UNIDADXEMBALAJE NUMBER NOT NULL,
	PESOXEMBALAJE NUMBER NOT NULL,
	INVEN_PISO1 NUMBER NOT NULL,
	INVEN_PISO2 NUMBER NOT NULL,
	INVEN_TOTAL NUMBER NOT NULL,
	FECHA_INVENTARIO DATE NOT NULL
) TABLESPACE CURSODB_DAT;

COMMENT ON TABLE CURSODB.TBL_HISTORICOSINVEN  IS 'HISTORICOS INVENTARIOS';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.COD_HISTORICO IS 'Codigo consecutivo del historico';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.COD_PRODUCTO IS 'Codigo del producto';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.NOMBRE IS 'Nombre de producto';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.PESOXUNIDAD IS 'Peso por unidad del producto';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.UNIDADXEMBALAJE IS 'Unidades por embalaje del producto';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.PESOXEMBALAJE IS 'Peso por embalaje del producto';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.INVEN_PISO1 IS 'Inventario del piso 1 del producto';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.INVEN_PISO2 IS 'Inventario del piso 2 del producto';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.INVEN_TOTAL IS 'Inventario total (piso 1 + piso 2) del producto';
COMMENT ON COLUMN CURSODB.TBL_HISTORICOSINVEN.FECHA_INVENTARIO IS 'Fecha de corte que se realizo el histroico del inventario';

CREATE UNIQUE INDEX IDX_PK_COD_HISTORICO_HISTOINVE
	ON CURSODB.TBL_HISTORICOSINVEN(COD_HISTORICO)
	TABLESPACE CURSODB_IDX;

ALTER TABLE CURSODB.TBL_HISTORICOSINVEN ADD CONSTRAINT PK_COD_HISTORICO_HISTOINVE PRIMARY KEY (COD_HISTORICO)
    USING INDEX IDX_PK_COD_HISTORICO_HISTOINVE;