--Consultar rutas de las tablespace
SELECT * FROM DBA_DATA_FILES;

--Creación de la TableSpace para los datos
CREATE TABLESPACE CURSOPLSQL_DAT 
    DATAFILE 'C:\ORACLE\ORADATA\ORCL\CURSOPLSQL_DAT.DBF' SIZE 5242880 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL;

--Creación de la TableSpace para los indices
CREATE TABLESPACE CURSOPLSQL_IDX 
    DATAFILE 'C:\ORACLE\ORADATA\ORCL\CURSOPLSQL_IDX.DBF' SIZE 5242880 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL;

--Si sale error al crear usuario ejecutar
alter session set "_ORACLE_SCRIPT"=true;

--Creación de usuario para las TableSpaces creadas anteriormente
CREATE USER "CURSOPLSQL" IDENTIFIED BY "cursoPLSQL2025"
DEFAULT TABLESPACE "CURSOPLSQL_DAT" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

--Permisos para el usuario
GRANT "CONNECT" TO "CURSOPLSQL";
GRANT "RESOURCE" TO "CURSOPLSQL";

--Permisos sobre los objetos
GRANT ALTER ANY INDEX TO "CURSOPLSQL";
GRANT ALTER ANY SEQUENCE TO "CURSOPLSQL";
GRANT ALTER ANY TABLE TO "CURSOPLSQL";
GRANT ALTER ANY TRIGGER TO "CURSOPLSQL";
GRANT CREATE ANY INDEX TO "CURSOPLSQL";
GRANT CREATE ANY SEQUENCE TO "CURSOPLSQL";
GRANT CREATE ANY SYNONYM TO "CURSOPLSQL";
GRANT CREATE ANY TABLE TO "CURSOPLSQL";
GRANT CREATE ANY TRIGGER TO "CURSOPLSQL";
GRANT CREATE ANY VIEW TO "CURSOPLSQL";
GRANT CREATE PROCEDURE TO "CURSOPLSQL";
GRANT CREATE PUBLIC SYNONYM TO "CURSOPLSQL";
GRANT CREATE TRIGGER TO "CURSOPLSQL";
GRANT CREATE VIEW TO "CURSOPLSQL";
GRANT DELETE ANY TABLE TO "CURSOPLSQL";
GRANT DROP ANY INDEX TO "CURSOPLSQL";
GRANT DROP ANY SEQUENCE TO "CURSOPLSQL";
GRANT DROP ANY TABLE TO "CURSOPLSQL";
GRANT DROP ANY TRIGGER TO "CURSOPLSQL";
GRANT DROP ANY VIEW TO "CURSOPLSQL";
GRANT INSERT ANY TABLE TO "CURSOPLSQL";
GRANT QUERY REWRITE TO "CURSOPLSQL";
GRANT SELECT ANY TABLE TO "CURSOPLSQL";
GRANT UNLIMITED TABLESPACE TO "CURSOPLSQL";