import { SlideViewer } from "@/components/slide-viewer"

export default function Week10Slides() {
  const slides = [
    {
      id: 1,
      title: "Primera Entrega del Proyecto",
      subtitle: "Módulo 3: Proyecto Final - Semana 10",
      type: "intro" as const,
      content: (
        <div className="text-center space-y-6">
          <h2 className="text-3xl font-bold text-purple-600">Primera Entrega del Proyecto</h2>
          <p className="text-xl text-gray-600">Sistema Bancario: MER, scripts DDL y pruebas iniciales</p>
          <div className="bg-purple-50 dark:bg-purple-900/20 p-6 rounded-lg">
            <p className="text-lg">Presentación del diseño de base de datos para el sistema de gestión bancaria</p>
          </div>
        </div>
      ),
    },
    {
      id: 2,
      title: "Objetivos de la Primera Entrega",
      type: "content" as const,
      content: (
        <div className="space-y-6">
          <div className="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-lg mb-4">
            <h3 className="text-lg font-bold text-purple-700 dark:text-purple-300">Avance del Proyecto: 50%</h3>
          </div>
          <ul className="space-y-4 text-lg">
            <li className="flex items-start gap-3">
              <span className="bg-blue-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                1
              </span>
              <span>Presentar el MER del sistema bancario con todas las entidades</span>
            </li>
            <li className="flex items-start gap-3">
              <span className="bg-blue-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                2
              </span>
              <span>Entregar scripts DDL para tablas bancarias funcionales</span>
            </li>
            <li className="flex items-start gap-3">
              <span className="bg-blue-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                3
              </span>
              <span>Implementar 50% de los paquetes PL/SQL (gestion_clientes_pkg y gestion_cuentas_pkg)</span>
            </li>
            <li className="flex items-start gap-3">
              <span className="bg-blue-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                4
              </span>
              <span>Demostrar inserción de datos de clientes y cuentas de prueba</span>
            </li>
            <li className="flex items-start gap-3">
              <span className="bg-blue-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                5
              </span>
              <span>Realizar pruebas de integridad referencial bancaria</span>
            </li>
            <li className="flex items-start gap-3">
              <span className="bg-blue-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                6
              </span>
              <span>Documentar decisiones de diseño del sistema bancario</span>
            </li>
          </ul>
        </div>
      ),
    },
    {
      id: 3,
      title: "Script DDL - Creación de Tablas Bancarias",
      type: "code" as const,
      content: (
        <div className="space-y-4">
          <p className="text-lg mb-4">Ejemplo de script DDL para sistema bancario:</p>
          <pre className="bg-gray-900 text-green-400 p-6 rounded-lg overflow-x-auto text-sm">
            <code>{`-- Script de creación de tablas para sistema bancario
-- Tabla de clientes
CREATE TABLE Cliente (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR2(200) NOT NULL,
    identificacion VARCHAR2(20) UNIQUE NOT NULL,
    direccion VARCHAR2(300),
    telefono VARCHAR2(20),
    email VARCHAR2(100),
    fecha_registro DATE DEFAULT SYSDATE,
    estado VARCHAR2(20) DEFAULT 'ACTIVO',
    CONSTRAINT ck_cliente_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- Tabla de cuentas
CREATE TABLE Cuenta (
    numero_cuenta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    tipo_cuenta VARCHAR2(20) NOT NULL,
    saldo NUMBER(15,2) DEFAULT 0,
    estado VARCHAR2(20) DEFAULT 'activa',
    fecha_apertura DATE DEFAULT SYSDATE,
    CONSTRAINT fk_cuenta_cliente FOREIGN KEY (cliente_id) REFERENCES Cliente(cliente_id),
    CONSTRAINT ck_cuenta_tipo CHECK (tipo_cuenta IN ('AHORROS', 'CORRIENTE', 'CDT')),
    CONSTRAINT ck_cuenta_estado CHECK (estado IN ('activa', 'inactiva', 'bloqueada'))
);`}</code>
          </pre>
        </div>
      ),
    },
    {
      id: 4,
      title: "Paquetes PL/SQL - Primera Entrega (50%)",
      type: "code" as const,
      content: (
        <div className="space-y-4">
          <p className="text-lg mb-4">Implementación de los primeros paquetes PL/SQL del sistema bancario:</p>
          <pre className="bg-gray-900 text-green-400 p-6 rounded-lg overflow-x-auto text-sm">
            <code>{`-- Paquete de Gestión de Clientes
CREATE OR REPLACE PACKAGE gestion_clientes_pkg AS
    PROCEDURE crear_cliente(
        p_nombre_completo VARCHAR2,
        p_identificacion VARCHAR2,
        p_direccion VARCHAR2,
        p_telefono VARCHAR2 DEFAULT NULL,
        p_email VARCHAR2 DEFAULT NULL
    );
    
    FUNCTION validar_cliente(p_cliente_id NUMBER) RETURN BOOLEAN;
    PROCEDURE actualizar_cliente(p_cliente_id NUMBER, p_direccion VARCHAR2);
END gestion_clientes_pkg;

-- Paquete de Gestión de Cuentas
CREATE OR REPLACE PACKAGE gestion_cuentas_pkg AS
    PROCEDURE crear_cuenta(
        p_cliente_id NUMBER,
        p_tipo_cuenta VARCHAR2,
        p_saldo_inicial NUMBER DEFAULT 0
    );
    
    PROCEDURE cambiar_estado_cuenta(
        p_numero_cuenta NUMBER,
        p_nuevo_estado VARCHAR2
    );
    
    FUNCTION consultar_saldo(p_numero_cuenta NUMBER) RETURN NUMBER;
END gestion_cuentas_pkg;`}</code>
          </pre>
        </div>
      ),
    },
    {
      id: 5,
      title: "Criterios de Evaluación",
      type: "content" as const,
      content: (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg">
              <h3 className="font-bold text-blue-700 dark:text-blue-300 mb-2">Completitud del MER</h3>
              <p className="text-2xl font-bold text-blue-600">25%</p>
            </div>
            <div className="bg-green-50 dark:bg-green-900/20 p-4 rounded-lg">
              <h3 className="font-bold text-green-700 dark:text-green-300 mb-2">Scripts DDL</h3>
              <p className="text-2xl font-bold text-green-600">20%</p>
            </div>
            <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg">
              <h3 className="font-bold text-red-700 dark:text-red-300 mb-2">Paquetes PL/SQL (50%)</h3>
              <p className="text-2xl font-bold text-red-600">25%</p>
            </div>
            <div className="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-lg">
              <h3 className="font-bold text-purple-700 dark:text-purple-300 mb-2">Datos de Prueba</h3>
              <p className="text-2xl font-bold text-purple-600">15%</p>
            </div>
            <div className="bg-orange-50 dark:bg-orange-900/20 p-4 rounded-lg">
              <h3 className="font-bold text-orange-700 dark:text-orange-300 mb-2">Documentación</h3>
              <p className="text-2xl font-bold text-orange-600">15%</p>
            </div>
          </div>
        </div>
      ),
    },
    {
      id: 6,
      title: "Entregables Requeridos",
      type: "exercise" as const,
      content: (
        <div className="space-y-6">
          <div className="bg-orange-50 dark:bg-orange-900/20 p-6 rounded-lg">
            <h3 className="text-xl font-bold mb-4 text-orange-700 dark:text-orange-300">
              Lista de Entregables (50% del Proyecto):
            </h3>
            <ul className="space-y-3">
              <li className="flex items-start gap-3">
                <span className="bg-orange-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                  1
                </span>
                <span>Diagrama MER del sistema bancario en formato PDF o imagen de alta calidad</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="bg-orange-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                  2
                </span>
                <span>Script DDL completo para tablas bancarias (crear_tablas_banco.sql)</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="bg-orange-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                  3
                </span>
                <span>Paquetes PL/SQL: gestion_clientes_pkg y gestion_cuentas_pkg completos</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="bg-orange-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                  4
                </span>
                <span>Script de datos de prueba bancarios (insertar_datos_banco.sql)</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="bg-orange-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                  5
                </span>
                <span>Documento de diseño explicando arquitectura del sistema bancario</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="bg-orange-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold">
                  6
                </span>
                <span>Scripts de prueba para validar funcionamiento de paquetes PL/SQL</span>
              </li>
            </ul>
          </div>
        </div>
      ),
    },
  ]

  return <SlideViewer slides={slides} moduleTitle="Módulo 3: Proyecto Final" weekNumber={10} />
}
